version: "3.8"

services:
  redis:
    image: redis:7.2.0
    container_name: redis
    restart: always
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - ./redis/insight:/db
