version: "3.8"

services:
  redis:
    image: redis:7.2.0
    container_name: redis
    restart: always
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - ./redis/insight:/db
  client:
    container_name: client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - 80:80
    depends_on:
      - redis
      - db
      - api
  api:
    container_name: api
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - 8080:8080 
      - 8888:8888
    depends_on:
      - redis
      - db
    environment:
      - NODE_ENV=production
  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/base:/var/lib/postgresql/data/
  pg_admin:
    container_name: pgadmin
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
